fix 8 with changes on azure

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,12 +21,12 @@ jobs:
         with:
           python-version: "3.10"
 
-      - name: Install Dependencies
+      - name: Install Dependencies 🔥
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Allow JSON Content
+      - name: Allow JSON Content 🧠
         run: |
           echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> $GITHUB_ENV
           echo "WEBSITES_PORT=5000" >> $GITHUB_ENV
@@ -45,5 +45,4 @@ jobs:
 
       - name: Purge Azure Cache 🔥
         run: |
-          curl -X POST "${{ secrets.AZURE_WEBAPP_URL }}/?nocache=true" || echo "Cache Purge Failed, but Deployment Successful!"
-        
+          curl -X POST "${{ env.AZURE_WEBAPP_URL }}/?nocache=true" || echo "Cache Purge Failed, but Deploy Successful!"
